USE sistema_pedidos;

INSERT INTO tbl_clientes (nome, cidade, uf)
VALUES
('Altair Mateus Toledo Alencastro', 'Camaquã', 'RS'),
('Carlos Eduardo da Silva', 'Londrina', 'PR'),
('Daniela Pacheco Toledo', 'Caxias do Sul', 'RS'),
('Eduardo Vasconcelos Nogueira', 'Joinville', 'SC'),
('Fernanda Lacerda', 'Blumenau', 'SC'),
('João Gustavo Moreira', 'Ribeirão Preto', 'SP'),
('Maria Helena Bittencourt da Silva', 'Santos', 'SP'),
('Igor Pinto Nascimento', 'São José dos Campos', 'SP'),
('Juliana Lucas', 'Sorocaba', 'SP'),
('Lucas Esteves da Silva', 'Campinas', 'SP'),
('Michelle Silva e Silva', 'Niterói', 'RJ'),
('Josnelson Alves da Silva', 'Petrópolis', 'RJ'),
('Livia Andrade', 'Volta Redonda', 'RJ'),
('Paulo José Brito', 'Juiz de Fora', 'MG'),
('Maria Roberta Lins', 'Montes Claros', 'MG'),
('Samuel Correia Lacerda', 'Aracaju', 'SE'),
('Tatiana Sales Nascimento', 'Palmas', 'TO'),
('Ubirajara Mendes da Silva', 'Cuiabá', 'MT'),
('Valentina Brito Toledo', 'Porto Velho', 'RO'),
('William Barbosa Moura', 'Macapá', 'AP'),
('Miguel Neumann', 'São José dos Campos', 'SP');

INSERT INTO tbl_produtos (descricao, preco_venda) VALUES
('Mouse Gamer RGB', 99.90),
('Teclado Mecânico ABNT2', 268.45),
('Monitor 24 Polegadas Full HD', 929.90),
('Notebook 8GB RAM SSD 256GB', 3215.30),
('Headset Bluetooth', 159.90),
('Webcam Full HD', 142.75),
('Cadeira Gamer Reclinável', 1199.00),
('Mesa para Escritório', 498.60),
('HD Externo 1TB', 329.90),
('Pen Drive 64GB', 36.20),
('Roteador Wi-Fi Dual Band', 239.90),
('Smartphone 128GB', 2018.55),
('Carregador Portátil 10000mAh', 94.90),
('Cabo USB-C 1m', 23.40),
('Caixa de Som Bluetooth', 149.90),
('Smartwatch Fitness', 312.80),
('Impressora Multifuncional', 839.90),
('Suporte para Notebook', 67.35),
('Luminária LED de Mesa', 84.90),
('Microfone USB Condensador', 214.60),
('Teclado Wireless Compacto', 129.90),
('Mousepad Extra Grande', 58.75),
('Adaptador HDMI para VGA', 39.90),
('Hub USB 4 Portas', 72.40),
('Cooler para Notebook', 89.90);